# Generated by Django 2.2.1 on 2019-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
