# Generated by Django 2.2.1 on 2019-06-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='submissionDate',
            new_name='submission_date',
        ),
    ]
